package api;

import model.ModelClassifier;
import model.ModelGenerator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import weka.classifiers.functions.MultilayerPerceptron;
import weka.core.*;
import weka.experiment.InstanceQuery;
import weka.filters.Filter;
import weka.filters.unsupervised.attribute.Normalize;

import java.io.File;
import java.util.HashMap;
import java.util.Map;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/eeg") // This means URL's start with /demo (after api.Application path)
public class EEGController {

    @Autowired // This means to get the bean called eegDataRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EEGDataRepository eegDataRepository;

    @PostMapping("/save")
    public @ResponseBody EEGData save(@RequestBody EEGData eegData) {
        return eegDataRepository.save(eegData);
    }

    @GetMapping("/get")
    public @ResponseBody
    Iterable<EEGData> get() {
        return eegDataRepository.findAll();
    }

    @PostMapping("/classify")
    public @ResponseBody
    String classify(@RequestBody EEGData eegData) throws Exception {

        ModelClassifier cls = new ModelClassifier();

        String modelPath ;
        if (System.getenv("ENV").equals("docker")) {
            modelPath = System.getenv("MODEL_PATH");
        } else {
            modelPath = ModelGenerator.class.getClassLoader().getResource("model.bin").getPath();
        }

        Instances clsInstances = cls.createInstance(eegData.getTheta(), eegData.getLowAlpha(), eegData.getHighAlpha(), eegData.getLowBeta(), eegData.getHighBeta(), eegData.getLowGamma(), eegData.getMidGamma(), eegData.getAttention(), eegData.getMeditation(), eegData.getBlink());

        String classname = cls.classify(clsInstances, modelPath);

        System.out.println("The class name for the instance with: \n" + clsInstances + " is " + classname);

        return classname;
    }

    @PostMapping("/updateModel")
    public @ResponseBody
    Map<String, String> updateModel() throws Exception {
        ModelGenerator mg = new ModelGenerator();

        String mysqlUser = System.getenv("DB_USERNAME");
        String mysqlPassword = System.getenv("DB_PASSWORD");
        String databaseUrl = "jdbc:mysql://" + System.getenv("DB_HOST") + ":" + System.getenv("DB_PORT") + "/" + System.getenv("DB_NAME");

        File databaseUtilsFile;
        if (System.getenv("ENV").equals("docker")) {
            databaseUtilsFile = new File(System.getenv("DATABASE_UTILS_PATH"));
        } else {
            ClassLoader classLoader = getClass().getClassLoader();
            databaseUtilsFile = new File(classLoader.getResource("DatabaseUtils.props").toURI());
        }

        InstanceQuery instanceQuery = mg.configDBConnection(databaseUtilsFile, mysqlUser, mysqlPassword, databaseUrl);

        String query = "SELECT theta, lowAlpha, highAlpha, lowBeta, highBeta, lowGamma, midGamma, attention, meditation, blink, feelingLabel FROM EEGData";
        Instances dataSet = mg.loadDatasetFromDB(instanceQuery, query);

        Filter filter = new Normalize();

        // Divide dataSet to train dataSet 80% and test dataSet 20%
        int trainSize = (int) Math.round(dataSet.numInstances() * 0.8);
        int testSize = dataSet.numInstances() - trainSize;

        dataSet.randomize(new Debug.Random(1));// if you comment this line the accuracy of the model will be dropped from 96.6% to 80%

        // Normalize dataSet
        filter.setInputFormat(dataSet);

        Instances dataSetNor = Filter.useFilter(dataSet, filter);

        Instances trainDataSet = new Instances(dataSetNor, 0, trainSize);
        Instances testDataSet = new Instances(dataSetNor, trainSize, testSize);

        // Build classifier with train DataSet
        MultilayerPerceptron ann = (MultilayerPerceptron) mg.buildClassifier(trainDataSet);

        // Evaluate classifier with test DataSet
        String evalSummary = mg.evaluateModel(ann, trainDataSet, testDataSet);
        System.out.println("Evaluation: " + evalSummary);

        // Save model
        String modelPath ;
        if (System.getenv("ENV").equals("docker")) {
            modelPath = System.getenv("MODEL_PATH");
        } else {
            modelPath = ModelGenerator.class.getClassLoader().getResource("model.bin").getPath();
        }
        mg.saveModel(ann, modelPath);

        Map<String, String> ret = new HashMap<>();
        ret.put("Status", "DONE");

        return ret;
    }
}